# Generated by Django 3.2.13 on 2022-06-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Invitation_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='招待コード'),
        ),
    ]
