# Generated by Django 3.2.13 on 2022-06-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacCategory', models.CharField(default='', max_length=50, verbose_name='BAC種別')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|BAC種別',
                'verbose_name_plural': '|マスタ定義|BAC種別',
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessCategory', models.CharField(default='', max_length=50, verbose_name='業務区分')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|業務区分',
                'verbose_name_plural': '|マスタ定義|業務区分',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='CATEGORY')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|CATEGORY',
                'verbose_name_plural': '|マスタ定義|CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='DelayReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delayReason', models.CharField(default='', max_length=30, verbose_name='遅延理由区分')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|遅延理由区分',
                'verbose_name_plural': '|マスタ定義|遅延理由区分',
            },
        ),
        migrations.CreateModel(
            name='FunctionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionalCategory', models.CharField(default='', max_length=50, verbose_name='機能区分')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|機能区分',
                'verbose_name_plural': '|マスタ定義|機能区分',
            },
        ),
        migrations.CreateModel(
            name='ImpactScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impactScope', models.CharField(max_length=20, verbose_name='影響範囲')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|影響範囲',
                'verbose_name_plural': '|マスタ定義|影響範囲',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='', max_length=30, verbose_name='工程')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|工程',
                'verbose_name_plural': '|マスタ定義|工程',
            },
        ),
        migrations.CreateModel(
            name='RiskIssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskIssueCategory', models.CharField(default='', max_length=50, verbose_name='分類（課題・リスク）')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|分類（課題・リスク）',
                'verbose_name_plural': '|マスタ定義|分類（課題・リスク）',
            },
        ),
        migrations.CreateModel(
            name='RiskResponseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskResponseType', models.CharField(default='', max_length=50, verbose_name='リスク対応タイプ')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|リスク対応タイプ',
                'verbose_name_plural': '|マスタ定義|リスク対応タイプ',
            },
        ),
        migrations.CreateModel(
            name='RiskScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskScope', models.CharField(default='', max_length=50, verbose_name='リスク種別')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|リスク種別',
                'verbose_name_plural': '|マスタ定義|リスク種別',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default='', max_length=30, verbose_name='STAGE')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|STAGE',
                'verbose_name_plural': '|マスタ定義|STAGE',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20, verbose_name='ステータス')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|ステータス',
                'verbose_name_plural': '|マスタ定義|ステータス',
            },
        ),
        migrations.CreateModel(
            name='SubSystemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subSystemCategory', models.CharField(default='', max_length=50, verbose_name='サブシステム区分')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|サブシステム区分',
                'verbose_name_plural': '|マスタ定義|サブシステム区分',
            },
        ),
        migrations.CreateModel(
            name='SubTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTeam', models.CharField(default='', max_length=30, verbose_name='サブチーム')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|サブチーム',
                'verbose_name_plural': '|マスタ定義|サブチーム',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='', max_length=30, verbose_name='チーム')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|チーム',
                'verbose_name_plural': '|マスタ定義|チーム',
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testType', models.CharField(default='', max_length=30, verbose_name='テスト種別')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|テスト種別',
                'verbose_name_plural': '|マスタ定義|テスト種別',
            },
        ),
        migrations.CreateModel(
            name='WorkSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workSite', models.CharField(default='', max_length=30, verbose_name='WorkSite')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|WORK SITE',
                'verbose_name_plural': '|マスタ定義|WORK SITE',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workType', models.CharField(default='', max_length=30, verbose_name='作業種別')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='COMMENTS')),
            ],
            options={
                'verbose_name': '|マスタ定義|作業種別',
                'verbose_name_plural': '|マスタ定義|作業種別',
            },
        ),
    ]
